NEWS_WEBAPP/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include, re_path

import blogs.views

from blogs import views
from django.conf import settings
from django.conf.urls.static import static
from profiles import views as profiles_views
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
                  path('admin/', admin.site.urls, name='admin'),
                  path('', views.home_view, name='home'),
                  path('about/', views.about_view, name='about'),

                  path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

                  path('addpost/', blogs.views.AddPost.as_view(), name='addpost'),
                  path('detailpost/edit/<int:pk>', blogs.views.UpdatePost.as_view(), name='updatepost'),
                  path('detailpost/<int:pk>', blogs.views.DetailPost.as_view(), name='detailpost'),
                  path('detailpost/<int:pk>/delete', blogs.views.DeletePost.as_view(), name='deletepost'),
                  path('detailpost/<int:pk>/comment', blogs.views.AddCommentPost.as_view(), name='addcomment'),

                  path('login/', profiles_views.login_register, name='login'),
                  path('profile/', profiles_views.ProfileSite.as_view(), name='profile'),
                  path('edit_profile/', profiles_views.update_profile, name='edit_profile'),

                  path('password/', profiles_views.PasswordChange.as_view(), name='changepass'),
                  path('logout/', profiles_views.LogoutSite.as_view(), name='logout'),
                    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  path('search', blogs.views.search_bar, name='search'),
                  path('detailpost/<int:pk>/del_comment', blogs.views.DeleteComment.as_view(), name='delcomment'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    body = RichTextField(blank=True,null=True)
    views = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='blogs.images')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detailpost', args=[str(self.id)])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(User,related_name="users",on_delete=models.CASCADE,default=None, null=True,blank=True)
    name = models.CharField(max_length=250)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)
    

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField()
    avatar = models.ImageField(null=True, blank=True, default="profiles.images/default_ava.png",
                               upload_to="profiles.images/")
    media_url = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return str(self.user)

profiles/views.py
from django.contrib import messages
from django.contrib.auth import logout, views, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from .models import Profile
from django.views.generic import TemplateView, FormView, UpdateView
from NEWS_WEBAPP.forms import CustomRegisterForm, CustomEditProfileForm, ProfileForm, CustomLoginForm


def login_register(request):
    if request.method == 'POST':
        register_form = CustomRegisterForm(request.POST)
        if 'signup' in request.POST:
            if register_form.is_valid():
                register_form.save()
                messages.success(request, f'Tạo tài khoản thành công !')
                new_user = authenticate(username=register_form.cleaned_data['username'],
                                        password=register_form.cleaned_data['password1'], )
                login(request, new_user)
                return redirect("login")
            else:
                email = register_form.cleaned_data.get('email')
                password1 = register_form.cleaned_data.get('password1')
                password2 = register_form.cleaned_data.get('password2')
                if password1 == password2:
                    messages.error(request, f'Tên tài khoản đã tồn tại')
                    return redirect('login')
                else:
                    messages.error(request, "Mật khẩu xác thực không khớp")
                    return redirect('login')
        elif 'login' in request.POST:
            log_view = views.LoginView.as_view(template_name='login.html')
            log_view(request)
            if request.user.is_authenticated:
                messages.success(request, 'Đăng nhập thành công')
            else:
                messages.error(request, 'Tài khoản không tồn tại')
            return redirect('login')
    else:
        if request.user.is_authenticated:
            return redirect('profile')
        else:
            register_form = CustomRegisterForm()
            login_form = CustomLoginForm(request)
            return render(request, 'login.html', {'register_form': register_form, 'login_form': login_form})


class LogoutSite(LogoutView):
    template_name = 'profile.html'


class ProfileSite(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'


@login_required
def update_profile(request):
    Profile.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        user_form = CustomEditProfileForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Cập nhật tài khoản thành công')
            return redirect('profile')
        else:
            messages.error(request, 'Vui lòng điền đúng định dạng')
    else:
        user_form = CustomEditProfileForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


class PasswordChange(PasswordChangeView):
    from_class = PasswordChangeView
    template_name = 'pass_change.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        form.save()
        self.request.session.flush()
        logout(self.request)
        messages.success(self.request, 'Đổi mật khẩu thành công')
        return super().form_valid(form)


# class LoginSite(SuccessMessageMixin, LoginView):
#     template_name = 'base.html'
#     redirect_authenticated_user = True
#     success_message = "Logged in successfully"

#
# class RegisterSite(FormView):
#     template_name = 'register.html'
#     form_class = CustomRegisterForm
#
#     def form_valid(self, form):
#         data = form.cleaned_data
#         new_user = User.objects.create_user(
#             username=data['username'],
#             password=data['password1'],
#             email=data['email']
#         )
#         messages.success(self.request, 'Register successful')
#         return redirect('login')

# class EditProfile(generic.UpdateView):
#     model = User
#     form_class = CustomEditProfileForm
#     template_name = "edit_profile.html"
#     success_url = '/profile/'
#
#     def get_object(self):
#         return self.request.user
#
#
# class BioProfileView(generic.UpdateView):
#     model = Profile
#     fields = ('bio', 'avatar', 'media_url')
#     template_name = 'bio_profile.html'
#     success_url = '/profile/'
#
#     def get_object(self):
#         return self.request.user

templates/about.html
{% extends 'base.html' %}
{% block content%}

<div style="margin:50px;text-align:justify">
    <h2 >Giới thiệu</h2>

<p style="margin-top: 20px;">Thời đại công nghệ 4.0 thì chắc hẳn không còn ai xa lạ với việc xem hoặc tra cứu thông tin từ những công cụ trực tuyến như Google, Bing, Youtube,… nói chung và các nền tảng website bán hàng, tin tức, báo chí nói riêng có thể kể đến tiêu biểu ở Việt Nam như VnExpress, BaoThanhNien, TuoiTre, DanTri,… chúng đã hoàn toàn thay thế được các phương thức trao đổi, cập nhật thông tin, phổ cập tin tức trước đây nhờ vào những lợi thế sau:</p>  
<ul style="margin-left: 30px;">
    <li style="font-weight: bold;"> Tính tiết kiệm:</li>
    <p>Tiếp cận nguồn thông tin, tin tức, tài nguyên gần như vô hạn miễn là có kết nối tới Internet thay vì phải bỏ tiền mua từng mảnh thông tin, tờ báo, cuốn sách như trước đây.</p>

    <li style="font-weight: bold;"> Tính đa dạng:</li>
    <p>Có thể tìm kiếm thông tin theo từ khóa, hashtag, danh mục, chủ đề … hoặc bằng bất cứ thứ gì được gợi lên trong suy nghĩ của người dùng.</p>
    
    <li style="font-weight: bold;"> Tính chính xác:</li>
    <p>Các trang báo hoặc thư viện thông tin chính thống, có uy tín sẽ luôn cung cấp thông tin mới nhất và chính xác nhất, các thông tin được kiểm tra và phê duyệt trước khi đăng tải sẽ giúp người dùng tiếp cận được nguồn thông tin đáng tin cậy bao gồm thông tin cơ bản và cả chuyên sâu.</p>

    <li style="font-weight: bold;"> Tính tương tác:</li>
    <p>Có thể bình luận, trao đổi ý kiến hoặc góp ý về một nội dung nào đó trực tuyến và luôn được cập nhật bình luận mới nhất giúp cho người đọc có thể nói lên quan điểm của mình hoặc học hỏi tiếp thu từ ý kiến của những đọc giả khác hay chỉ đơn thuần là đóng góp, góp ý cho tác giả của bài viết.</p>
</ul>


<i>Những công nghệ, nền tảng sử dụng để thực hiện dự án:</i>
<ul style="margin-left: 30px;">
    
    <li style="font-weight: bold;"> BackEnd:</li>
    <p> Python, Django Framework, Deep Learning Natural Language Processing, Data Crawling.</p>

    <li style="font-weight: bold;"> FrontEnd:</li>
    <p>HTML5, CSS, JS, Bootstrap, JQuery.</p>

    <li style="font-weight: bold;"> Database:</li>
    <p>PostgreSQL.</p>
</ul>
</div>

      

{% endblock %}
</html>

templates/add_post.html
{% extends 'base.html' %}

{% block content %}
<div class="mainprofile row">
   <h2 style="margin-bottom: 50px;">Thêm bài viết</h2>
   <div class="col-md-12 editprofile">
      <form method="post" enctype="multipart/form-data">
         {%  csrf_token %}
          <div class="form-group">
             {{ form.media }}
             {{ form.as_p }}
      </div>
         <div class="text-right">
            <input type="button" style=" border-radius: 5px;" class="btn btn-danger mt-3" value="Thoát"
            onclick="location.href='/'"/>
            <button type="submit" style="margin-left: 20px; border-radius: 5px;" class="btn btn-primary mt-3">Thêm bài viết</button>
         </div>
          
      </form>
       <br>
   </div>
</div>
         
{% endblock %}

templates/base.html
<!doctype html>
<html>

{% load static %}
<!-- <script>
  var myModal = document.getElementById('myModal')
  var myInput = document.getElementById('myInput')

  myModal.addEventListener('shown.bs.modal', function () {
      myInput.focus()
  })
</script> -->
<head>
    {% block header %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
                crossorigin="anonymous"></script>

        <link href=" {% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'prettyPhoto/prettyPhoto.css' %}" type="text/css">
        <link href="{% static 'css1/owl.transitions.css' %}" rel="stylesheet">
        <link href="{% static 'css1/owl.carousel.css' %}" rel="stylesheet">
        <link href="{% static 'css1/style.css' %}" rel="stylesheet">
        <link href="{% static 'css1/responsive.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% endblock %}
    <title>{% block title %}News website application{% endblock %}</title>
</head>
<script>
    var m = document.getElementsByClassName("alert");  // Return an array

    setTimeout(function () {
        if (m && m.length) {
            m[0].classList.add('hide');
        }
    }, 3000);
    function check() {
		if (document.getElementById('id_password1').value == document
				.getElementById('id_password2').value) {
			document.getElementById('message1').style.cssText = "color: green; font-weight: bold; font-size: 13px; padding-left: 76px"
			document.getElementById('message2').style.cssText = "color: green; font-weight: bold; font-size: 13px; padding-left: 50px"
			document.getElementById('message1').innerHTML = "Mật khẩu trùng khớp ";
			document.getElementById('message2').innerHTML = "Mật khẩu trùng khớp ";
		} else {
			document.getElementById('message1').style.cssText = "color: red; font-weight: bold; font-size: 13px; padding-left: 76px"
			document.getElementById('message2').style.cssText = "color: red; font-weight: bold; font-size: 13px; padding-left: 50px"
			document.getElementById('message1').innerHTML = "Mật khẩu không khớp";
			document.getElementById('message2').innerHTML = "Mật khẩu không khớp";
		}
	}


</script>

<body data-spy="scroll" data-target="#bs-example-navbar-collapse-1">

<!--=========================nav========================-->


<section class="top_header" id="top">
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"><a href="/"><img src="{% static 'images/logo.png' %}" class="img-responsive"></a>
            </div>

            <div class="col-md-4"></div>

        </div>
    </div>

</section>

<div class="nav_header">
    <nav class="navbar navbar-default" id="Home">
        <div class="container-fluid">
            <div class="col-md-2 hiden_responsive">

                <div class="social hiden_responsive">
                    <i class="open fa fa-share-alt"></i>
                    <ul>
                        <li><a href="#"><i class="icon fa fa-facebook-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-square"></i></a></li>
                    </ul>
                </div>

            </div>
            <div class="col-md-10">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="row">
                    <div class="navbar-header col-sm-12">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span
                                class="sr-only">Toggle
                  navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                                class="icon-bar"></span></button>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
                            <div class="row">
                                <div class="col-sm-8">
                                    <ul class="nav navbar-nav navbar-left">
                                        <li><a href="/" class="padd_0">Trang chủ</a></li>
                                        <li><a href="#">Liên Hệ</a></li>
                                        <li><a href="{% url 'about' %}">Giới thiệu</a></li>
                                        {% if user.is_authenticated %}
                                            <li><a href="{% url 'addpost' %}">Thêm bài viết</a></li>
                                            {% if user.is_superuser %}
                                                <li><a href="/admin/">Admin</a></li>
                                            {% endif %}
                                        {% endif %}

                                    </ul>
                                </div>
                                <div class="col-sm-2">
                                    <form action="{% url 'search' %}" method="POST" class="hiden_responsive search">
                                        {% csrf_token %}
                                        <input type="text" name="search" value="" class="search-field" placeholder="Tìm tiêu đề bài viết..." required>
                                        <button type="submit"><i class="fa fa-search"></i></button>
                                    </form>

                                </div>
                                {% if user.is_authenticated %}
                                    <div class="col-sm-2 buttonlogin ">

                                        <ul class="nav navbar-nav navbar-right ">
                                            <li class="nav-item dropdown Profilemenu1">
                                                <a href="javascript:void(0)" class="dropdown-toggle user-link  nav-link"
                                                   data-toggle="dropdown">
                                                <span class="user-img">
                                                    {% if user.profile.avatar %}
                                                    <img class="rounded-circle" src="{{ user.profile.avatar.url }}"  >
                                                    {% else %}
                                                    <img class="rounded-circle" src="https://www.vippng.com/png/full/385-3856307_png-file-svg-user-icon.png" width="40" height="40">
                                                {% endif %}
                                              </span>
                                                </a>
                                                <div class="dropdown-menu Profilemenu">
                                                    <ul>
                                                        <li><a class="dropdown-item "
                                                               onclick="location.href=`{% url 'profile' %}`">Thông tin cá nhân</a>
                                                        </li>
                                                        <li><a class="dropdown-item "
                                                               onclick="location.href=`{% url 'logout' %}`">Đăng xuất</a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </li>
                                            <li class="prohiden">
                                                <button type="button" onclick="location.href=`{% url 'profile' %}`">
                                                    Thông tin cá nhan
                                                </button>
                                            </li>
                                            <li class="prohiden prohiden1">
                                                <button type="button" onclick="location.href=`{% url 'logout' %}`">
                                                    Đăng xuất
                                                </button>
                                            </li>
                                        </ul>

                                    </div>
                                {% else %}
                                    <div class="col-sm-2 buttonlogin">
                                        <ul class="nav navbar-nav navbar-right">
                                            <li>
                                                <button type="button" onclick="location.href=`{% url 'login' %}`">
                                                    Đăng nhập
                                                </button>
                                            </li>
                                        </ul>
                                    </div>
                                {% endif %}

                            </div>

                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                </div>

            </div>


        </div>
    </nav>
</div>

<!--=========================nav end ========================-->


<div class="message">
    {% for message in messages %}
        <div {% if message.tags %}
            class="alert alert-{{ message.tags }} alert-sm text-center" {% endif %}><h5>{{ message }}</h5></div>
    {% endfor %}
</div>
<div class="container mainnew mt-10 mb-5">
    {% block content %}{% endblock %}
</div>


<section class="footer" id="link">
    <div class="container mt-5">
        <div style="width: 30%; float:left" class="tennhom">
            Nguyễn Lê Hà <br>
            Đỗ Phương Anh <br>
            Nguyễn Quốc Bảo <br>
        </div>
        <div style="width: 40%; float:left">
            <a href="index.html"><a href="/"><img src="{% static 'images/logo.png' %}" class="img-responsive"></a>
        </div>

        <div style="width: 30%; float:left" class="text-right tennhom">
            <a href="#top">Back top</a>
        </div>

    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
<script src="{% static 'js1/jquery.min.js' %}"></script>
<script src="{% static 'prettyPhoto/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js1/main-script.min.js' %}"></script>
<script src="{% static 'js1/index.js' %}"></script>
<div class="none">
    <div class="copytext">Design By <a href="http://html5load.com/" target="_blank"
                                       class="copylink">html5load.Com</a></div>
</div>
</body>

</html>

templates/detail_post.html
{% extends 'base.html' %}


{% block content %}

       <!--========================= main content ========================-->
    
       <section class="main_content" style="margin-top: 50px;">
        <h1 id>{{ post.title }}</h1>
        <div> <small>Viết bởi: </small> <b>{{ post.author.first_name}} {{ post.author.last_name }}</b> </div>
        <small>Đăng vào ngày: {{ post.date }}</small><br> 
        <form method="POST" action="{% url 'deletepost' post.pk %}" onsubmit="return confirm('Are you sure ?');">
            {% csrf_token %}
            
            {% if user.is_authenticated %}
                {% if post.author.id == user.id %}
                    <input class="btn btn-primary mt-3" style="margin-right: 20px; border-radius: 5px;" type="button"
                           onclick="location.href=`{% url 'updatepost' post.pk %}`" value="Sửa"/>
                    <button type="submit"  style=" border-radius: 5px;" class="btn btn-danger mt-3">Xóa</button>
                {% endif %}
            {% endif %}
        </form>
        
        
        <div class="container">
            <div class="row">
    
            <!--=========================content left ========================-->
            <div class="col-md-9">
              <div class="row">
                  
                <!--=============RECENT headline ==============-->
                
                <div class="col-md-12 title mb30 maindetail">
                   
                    <p style="font-size: 18px; text-align:justify">{{ post.body|safe }}</p>
                </div>
           
              </div>
            </div>
            <!--=========================content left end ========================-->
    
            <!--=========================content middle ========================-->
    
            <div class="col-md-3">
    
              <!--=============TECHNOLOGY ==============-->
              <div class="row">
                <div class="col-md-12 title mb30">
                  <h5>Danh sách báo mới</h5>
                </div>
    
                <div class="col-md-12 mb30">
                  <div class="tecnology">
                    {% for posts in other_posts|slice:":10" %}
                      {% if forloop.first %}
                        <div class="content_box">
                          <span>
                            <i class="fa fa-clock-o"></i> {{ posts.date}} - Mới
                          </span>
                          <h6><a href="{% url 'detailpost' posts.pk %}">{{ posts.title }}</a></h6>
                        </div>
                      {%  else  %}
                      <hr>
                      <div class="content_box">
                        <span>
                          <i class="fa fa-clock-o"></i> {{ posts.date}} 
                        </span>
                        <h6><a href="{% url 'detailpost' posts.pk %}">{{ posts.title }}</a></h6>
                      </div>
                      {% endif %}
                    {% endfor %}
                  </div>
                </div>
              </div>
              <!--=============TECHNOLOGY end ==============-->
    
            </div>
    
            <!--=========================content middle end ========================-->
            
            </div>
            <div class="row">
              <div class="col-md-9">
                <h3>Bình luận</h3>
                {% if user.is_authenticated %}
                <form method="post" enctype="multipart/form-data" action="{% url 'addcomment' post.pk %}">
                  {% csrf_token %}

                  <textarea rows="3" name="body" required id="id_body" class="cmt" placeholder="Bình luận của bạn"></textarea>
                  <button type="submit" class="btn btn-success mx-1" style="float: right; margin-top:10px; border-radius:5px">Gửi</button>
                  <input type="text" name="name" required class="tencmt" id="id_name" value=" {{ user.first_name }} {{ user.last_name }}" readonly>
                  <div class="hrrr"></div>
                </form>








                








                {% else %}
                  <a style="font-size: 20px; margin: 20px 0px;" href="{% url 'login' %}">Đăng nhập </a>
                {% endif %}
                
                {% if not post.comments.all %}
                <br>
                
                <h5>Chưa có bình luận...</h5><br>
                {% else %}
                {% for cmt in post.comments.all %}
                <div class="phancmt">
                  <h5>{{ cmt.name }} <small> - {{ cmt.date_added }}</small></h5>
                  <div class="deleteee">
                      {% if cmt.author.id == user.id %}
                      <form method="post" enctype="multipart/form-data" action="{% url 'delcomment' cmt.pk %}" onsubmit="return confirm('Are you sure ?');">
                      {% csrf_token %}
                      

                      
                          <button type="submit"><i class="fa fa-trash"></i></button>
                       




                      </form>
                      {% else %}
                      
                      {% endif %}
                  </div>
                  
                  <p style="font-size: 15px">{{ cmt.body }}</p>
                </div>
                
                
                  


                {% endfor %}
                {% endif %}
              </div>
            </div>
     


        </div>
      </section>
{% endblock %}

templates/edit_profile.html
{%  extends 'base.html' %}

{% block content %}
<div class="mainprofile row">
    <h2 style="margin-bottom: 50px;">Sửa thông tin cá nhân</h2>
    <div class="col-md-12 editprofile">
        <form method="post" enctype='multipart/form-data' onsubmit="return confirm('Are you sure ?')">
            {%  csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <div class="text-right">
                    <input type="button" style=" border-radius: 5px;" class="btn btn-danger mr-1 mt-3" value="Thoát"
                                   onclick="location.href=`{% url 'profile' %}`"/>
                <button type="submit" style="margin-left: 20px; border-radius: 5px;" class="btn btn-primary mt-3 ml-3">Cập nhật</button>
                </div>
                
        </form>
        
        <br>
    </div>
</div>
{% endblock %}

templates/pass_change.html
{% extends 'base.html' %}


{% block content %}
<div class="centerllogin changepw">
    <div class="headerlogin">Đổi mật khẩu</div>
    <form method="post" onsubmit="return confirm('Are you sure ?')">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="button" class="btn btn-danger " value="Thoát"
                           onclick="window.history.back()"/>
        <input type="submit" value="Đổi mật khẩu">
       
        
    </form>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block content %}

    {% if not search_content.all  %}
        <h1 style="margin-top: 50px;">Tìm kiếm cho "{{ searched }}"</h1>
        <h2>Không tìm thấy</h2>
        {% else %}
        <h1 style="margin-top: 50px;">Tìm kiếm cho "{{ searched }}"</h1><br><br>
        {% for content in search_content %}
     
        <div class="timkiem">
            <a href="{% url 'detailpost' content.pk %}"><h3 style="display: block;">{{ content.title }}</h3></a>
            <span class="tag">{{ content.author.first_name}} {{ content.author.last_name }}</span>
                <time><i class="fa fa-clock-o"></i>{{ content.date }}</time>

            <div>
              <p>{{ content.body|safe }}</p>
            </div>
        </div>
     
        
      
        {% endfor %}
    {% endif %}
  
    

{% endblock %}